#include "anaport/options.hpp"
#include "anaport/model.hpp"   // FindingSeverity
#include <iostream>
#include <stdexcept>
#include <cstring>

namespace anaport {

void print_usage(const char* program_name) {
    std::cerr <<
        "Usage: " << program_name << " <source_dir> --out <output_dir>\n"
        "       [--build-dir <build_dir>] [--keep-build-dir] [--verbose]\n"
        "       [--include-utility-targets]\n"
        "       [--min-severity info|warning|error] [--no-info]\n"
        "       [-j] [-m] [-g]  (output format flags)\n"
        "\n"
        "Arguments:\n"
        "  <source_dir>              Path to the CMake project source root\n"
        "  --out <output_dir>        Directory where reports will be written\n"
        "\n"
        "Options:\n"
        "  --build-dir <path>        Use this directory for CMake configure (default: tmp)\n"
        "  --keep-build-dir          Do not remove build directory after analysis\n"
        "  --verbose                 Print extra diagnostic information\n"
        "  --include-utility-targets Include CTest dashboard/service UTILITY targets\n"
        "                            (Continuous*, Experimental*, Nightly*) in analysis.\n"
        "                            By default these are excluded.\n"
        "\n"
        "Severity filtering:\n"
        "  --min-severity <level>    Minimum severity to include in reports.\n"
        "                            Levels: info (default) | warning | error\n"
        "  --no-info                 Alias for --min-severity warning\n"
        "\n"
        "Output format flags (default: all three reports):\n"
        "  -j, --json                Generate report.json\n"
        "  -m, --markdown            Generate report.md (Markdown)\n"
        "  -g, --graph               Generate dependencies.dot (Graphviz)\n"
        "  Combinations:  -jm, -jg, -mg, -jmg all work\n"
        "  If none of -j/-m/-g is given, all three reports are generated.\n"
        "\n"
        "  --help, -h                Show this help and exit\n"
        "\n"
        "Output files (generated by default or when the corresponding flag is set):\n"
        "  report.json       Machine-readable portability analysis\n"
        "  report.md         Human-readable Markdown report\n"
        "  dependencies.dot  Graphviz dependency graph\n"
        "\n"
        "Examples:\n"
        "  " << program_name << " ./my_project --out ./reports\n"
        "  " << program_name << " ./my_project --out ./reports --build-dir /tmp/mybuild --verbose\n"
        "  " << program_name << " ./my_project --out ./reports --include-utility-targets\n"
        "  " << program_name << " ./my_project --out ./reports -jm --no-info\n"
        "  " << program_name << " ./my_project --out ./reports -g --min-severity warning\n";
}

/// Parse combined short flags like -jmg, -jm, -mg, -j, -m, -g
/// Returns true if the argument was a recognized combined short flag.
static bool parse_short_format_flags(const std::string& arg, Options& opts) {
    if (arg.size() < 2 || arg[0] != '-' || arg[1] == '-') return false;
    // All chars after '-' must be format flag chars
    bool any = false;
    bool all_format = true;
    for (size_t k = 1; k < arg.size(); ++k) {
        char c = arg[k];
        if (c == 'j') { opts.out_json = true; any = true; }
        else if (c == 'm') { opts.out_markdown = true; any = true; }
        else if (c == 'g') { opts.out_graphviz = true; any = true; }
        else { all_format = false; break; }
    }
    return any && all_format;
}

Options parse_options(int argc, char* argv[]) {
    if (argc < 2) {
        print_usage(argv[0]);
        throw std::runtime_error("Insufficient arguments");
    }

    Options opts;
    bool has_source = false;
    bool has_out = false;

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];

        if (arg == "--help" || arg == "-h") {
            print_usage(argv[0]);
            std::exit(0);
        } else if (arg == "--verbose" || arg == "-v") {
            opts.verbose = true;
        } else if (arg == "--keep-build-dir") {
            opts.keep_build_dir = true;
        } else if (arg == "--include-utility-targets") {
            opts.include_utility_targets = true;
        } else if (arg == "--no-info") {
            opts.min_severity = SeverityFilter::Warning;
        } else if (arg == "--min-severity") {
            if (i + 1 >= argc) throw std::runtime_error("--min-severity requires an argument (info|warning|error)");
            std::string level = argv[++i];
            if (level == "info")    opts.min_severity = SeverityFilter::Info;
            else if (level == "warning") opts.min_severity = SeverityFilter::Warning;
            else if (level == "error")   opts.min_severity = SeverityFilter::Error;
            else throw std::runtime_error("Unknown severity level: " + level + " (use info|warning|error)");
        } else if (arg == "--json") {
            opts.out_json = true;
        } else if (arg == "--markdown") {
            opts.out_markdown = true;
        } else if (arg == "--graph") {
            opts.out_graphviz = true;
        } else if (arg == "--out") {
            if (i + 1 >= argc) throw std::runtime_error("--out requires an argument");
            opts.output_dir = argv[++i];
            has_out = true;
        } else if (arg == "--build-dir") {
            if (i + 1 >= argc) throw std::runtime_error("--build-dir requires an argument");
            opts.build_dir = argv[++i];
        } else if (arg.size() >= 2 && arg[0] == '-' && arg[1] != '-') {
            // Try combined short flags: -j, -m, -g, -jmg, etc.
            if (parse_short_format_flags(arg, opts)) {
                // handled
            } else if (arg == "-v") {
                opts.verbose = true;
            } else if (arg == "-h") {
                print_usage(argv[0]);
                std::exit(0);
            } else {
                throw std::runtime_error("Unknown option: " + arg);
            }
        } else if (arg[0] != '-') {
            if (has_source) throw std::runtime_error("Multiple source directories specified");
            opts.source_dir = arg;
            has_source = true;
        } else {
            throw std::runtime_error("Unknown option: " + arg);
        }
    }

    if (!has_source) {
        print_usage(argv[0]);
        throw std::runtime_error("Source directory is required");
    }
    if (!has_out) {
        print_usage(argv[0]);
        throw std::runtime_error("--out <output_dir> is required");
    }

    // Make paths absolute
    opts.source_dir = std::filesystem::absolute(opts.source_dir);
    opts.output_dir = std::filesystem::absolute(opts.output_dir);
    if (!opts.build_dir.empty()) {
        opts.build_dir = std::filesystem::absolute(opts.build_dir);
    }

    return opts;
}

} // namespace anaport
